name: Lint

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-taplo-0.10.0
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install taplo
        run: |
          if ! command -v taplo >/dev/null || [[ "$(taplo --version)" != "taplo 0.10.0" ]]; then
            cargo +stable install taplo-cli --version 0.10.0 --locked
          fi

      - run: taplo fmt --check

