name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build(debug)
      run: cargo build --verbose
    - name: Build(release)
      run: cargo build --release --verbose
   
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests(debug)
        run: cargo test --verbose
      - name: Run tests(release)
        run: cargo test --release --verbose 
