name: Test

on:
  workflow_call:
    inputs:
      rust_toolchain:
        type: string
        required: true
      allow_failure:
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.allow_failure }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
      - run: cargo +${{ inputs.rust_toolchain }} check --workspace --all-targets --all-features --verbose
        continue-on-error: ${{ inputs.allow_failure }}
      - run: cargo +${{ inputs.rust_toolchain }} check --release --workspace --all-targets --all-features --verbose
        continue-on-error: ${{ inputs.allow_failure }}

  test:
    runs-on: ubuntu-latest
    needs: [check]
    continue-on-error: ${{ inputs.allow_failure }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
      - run: cargo +${{ inputs.rust_toolchain }} test --workspace --all-features --no-fail-fast --verbose
        continue-on-error: ${{ inputs.allow_failure }}
      - run: cargo +${{ inputs.rust_toolchain }} test --release --workspace --all-features --no-fail-fast --verbose
        continue-on-error: ${{ inputs.allow_failure }}
